#!/bin/bash
./build /scratch/lcph222/Xinan/lothelloClassifier/metagenomics/total/total_taxo_info/taxoInfo/overall.txt /scratch/xli262/ThisIsYY/31merShortTxt/ .Kmer $1 6 /scratch/xli262/ThisIsYY/map$1/$1.map /scratch/xli262/ThisIsYY/map$1/ 
